export const REG_USUARIO = 'REG_USER';
export const REG_SOLICITUD_CONTRATO = 'REG_HIRING_CONTRACT';
export const CONF_SERVICIOS = 'CONF_SERVICES';
export const CONSULTAR_MAPA_RECURSOS = 'QUERY_RESOURCES_MAP';
export const CONSULTAR_MAPA_SERVICIO = 'QUERY_SERVICES_MAP';
export const BANDEJA_APROBACION_CONTRATO = 'CONTRACT_APPROVAL_INBOX';

export const authorizations: Authorizations = {
  DELIVERY_MANAGER: [
    REG_USUARIO,
    REG_SOLICITUD_CONTRATO,
    CONF_SERVICIOS,
    CONSULTAR_MAPA_RECURSOS,
    CONSULTAR_MAPA_SERVICIO,
  ],
  PROJECT_MANAGER: [
    REG_SOLICITUD_CONTRATO,
    CONF_SERVICIOS,
    CONSULTAR_MAPA_SERVICIO,
  ],
  RRHH: [
    REG_SOLICITUD_CONTRATO,
    BANDEJA_APROBACION_CONTRATO,
    CONSULTAR_MAPA_RECURSOS,
  ],
  ANALYST: [REG_SOLICITUD_CONTRATO],
  GG: [BANDEJA_APROBACION_CONTRATO],
};

export interface Authorizations {
  DELIVERY_MANAGER: string[];
  PROJECT_MANAGER: string[];
  RRHH: string[];
  ANALYST: string[];
  GG: string[];
}
